name: officecore_example
description: Demo for creating a Excel file using syncfusion_flutter_officecore package.

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.0.5
  open_file: ^3.0.3
  syncfusion_flutter_xlsio:
    path: ../../syncfusion_flutter_xlsio


# The following section is specific to Flutter. 
flutter:
  uses-material-design: true
